# Generated by Django 4.2.5 on 2023-10-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_app',
            name='Type',
            field=models.CharField(choices=[('oncology', 'oncology'), ('neurology', 'neurology'), ('opthamology', 'opthamology'), ('cardiology', 'Cardiology'), ('pshycology', 'pshycology')], max_length=20, null=True, verbose_name='Type '),
        ),
    ]
