# Generated by Django 4.2.5 on 2023-10-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ai_app_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_app',
            name='Type',
            field=models.CharField(choices=[('neurology', 'neurology'), ('cardiology', 'Cardiology'), ('oncology', 'oncology'), ('pshycology', 'pshycology'), ('opthamology', 'opthamology')], max_length=20, null=True, verbose_name='Type '),
        ),
    ]
