# Generated by Django 4.1.3 on 2023-09-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userprofile_has_subscribed_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Credit use'), (4, 'Payment'), (3, 'Credit expire'), (1, 'Credit gain')]),
        ),
    ]
