# Generated by Django 4.1.3 on 2023-09-29 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_amount', models.FloatField(blank=True, null=True)),
                ('unique_payment_id', models.TextField(blank=True, max_length=500, null=True)),
                ('unique_id_for_user', models.TextField(blank=True, max_length=500, null=True)),
                ('payment_status', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
